"""add relationship in user table and ticket table

Revision ID: a922fde4e2e6
Revises: 5d8ace4dd4ae
Create Date: 2026-01-14 14:28:03.858559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a922fde4e2e6'
down_revision: Union[str, Sequence[str], None] = '5d8ace4dd4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=True)
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
